travis:
  secure:
    BINSTAR_TOKEN: sjpzQ75dtWPFe3w7+PQCO+uCwfBedYspyLQ1CCSiJJcAMhu8R2Wd2UBKSXQ6t7cjsLG2V+pSNQ0oK7HPE4388taruAhFCI4K4WZCsBif4e2OyNxl0gZk1/kUxklb2pPETJ3qrbcTWd8qbq6Y+7xz7v5TB8LPmdUPh9M3pxFNZtSEmBmSyUCh0XmGXRpvZqbdMfpEfXEZOmJjPd0Up2sXB63+ZvRxM+16pSPaQXqyADQlDPQHPmPYe4OdY2AduKewcsYOP0qyJvpPvJ/0FubeIRNRzb8b51O3yPKjWebn+GtZRoKgkMAGPOzR9V3SFNfvr0nTl0+leHXcyfwiQB+SXd74Mbu7n6UwsKM4Tq/oAksBes69S8H2eh5uDAdnPEhRt4KFYjh14GRwlEunpZSiE04/dueRORfrXz+ppIhbFQ0TUV3nXBPjSmzrIUVD+ZAD1u2enxtLsAAUF0FfO2G0+/0NylKMe5mG/EaOy5k/o6P2i7CxVGTr/2SP6g70+TzSC2Op+CC2zImFpqcuNwgC9yjvVTlTQiK+y0uUgsW2S4hJ6o94G8TEfaFoslJtGhtRUoBu/En2yj93tS6U68mzYxhdULV3ThfsiJjCt4z9Wk68IR/xFRt5baFSPj3MWzhMNj+U2UQNlxNT8Rw93/2DUUpypsKOGYIbErGSyRQmtpE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
